
[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
web_threads = {path = "../web_threads"}
routers = {path = "../routers"}
request_response = {path = "../request_response"}
httparse = "1"